/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Location = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const Ngo = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'focusArea' : IDL.Text,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'registrationNo' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const TourismService = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'provider' : IDL.Text,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : Location,
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const LuxuryDebtService = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'applicantName' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'amountRequested' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'contact' : ContactInfo,
  'radiologyCriteria' : IDL.Text,
  'name' : IDL.Text,
  'phisoCourses' : IDL.Vec(IDL.Text),
  'accreditation' : IDL.Text,
  'phisoPractices' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MedicalRecord = IDL.Record({
  'documents' : IDL.Vec(ExternalBlob),
  'patientId' : IDL.Text,
  'treatment' : IDL.Text,
  'diagnosis' : IDL.Text,
  'patientName' : IDL.Text,
  'recordId' : IDL.Text,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Text,
  'documents' : IDL.Vec(ExternalBlob),
  'labResults' : IDL.Vec(MedicalRecord),
  'userId' : IDL.Text,
  'imagingStudies' : IDL.Vec(ExternalBlob),
  'medications' : IDL.Vec(IDL.Text),
  'medicalHistory' : IDL.Vec(IDL.Text),
  'personalInfo' : IDL.Record({
    'dob' : IDL.Text,
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'gender' : IDL.Text,
  }),
  'allergies' : IDL.Vec(IDL.Text),
});
export const ResearchProject = IDL.Record({
  'title' : IDL.Text,
  'researchers' : IDL.Vec(IDL.Text),
  'institution' : IDL.Text,
  'dataFiles' : IDL.Vec(ExternalBlob),
  'ethicsApproval' : IDL.Bool,
  'fundingSource' : IDL.Text,
  'projectId' : IDL.Text,
  'abstract' : IDL.Text,
});
export const HealthcareProfessional = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'experience' : IDL.Nat,
  'credentials' : IDL.Vec(ExternalBlob),
  'specialties' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'professionalProfile' : IDL.Opt(HealthcareProfessional),
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AmbulanceRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'location' : Location,
});
export const HealthcareProfessionalRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'experience' : IDL.Nat,
  'credentials' : IDL.Vec(ExternalBlob),
  'specialties' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const NgoRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'focusArea' : IDL.Text,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'registrationNo' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const VendorRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const RecordFilter = IDL.Record({
  'patientId' : IDL.Opt(IDL.Text),
  'diagnosis' : IDL.Opt(IDL.Text),
  'dateRange' : IDL.Opt(
    IDL.Record({ 'endDate' : IDL.Text, 'startDate' : IDL.Text })
  ),
});
export const ResearchFilter = IDL.Record({
  'institution' : IDL.Opt(IDL.Text),
  'ethicsApproval' : IDL.Opt(IDL.Bool),
  'keyword' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCorporateHealthcareServices' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addNgo' : IDL.Func([Ngo], [], []),
  'addTourismService' : IDL.Func([TourismService], [], []),
  'addVendor' : IDL.Func([Vendor], [], []),
  'applyForLuxuryDebt' : IDL.Func([LuxuryDebtService], [], []),
  'approveAmbulance' : IDL.Func([IDL.Text], [], []),
  'approveHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
  'approveNgo' : IDL.Func([IDL.Text], [], []),
  'approveVendor' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCorporateHealthcare' : IDL.Func([Hospital], [], []),
  'createHealthRecord' : IDL.Func([HealthRecord], [], []),
  'createRecord' : IDL.Func([MedicalRecord], [], []),
  'createResearchProject' : IDL.Func([ResearchProject], [], []),
  'deleteRecord' : IDL.Func([IDL.Text], [], []),
  'filterDataByLocation' : IDL.Func(
      [Location],
      [
        IDL.Record({
          'professionals' : IDL.Vec(HealthcareProfessional),
          'vendors' : IDL.Vec(Vendor),
          'ngos' : IDL.Vec(Ngo),
          'hospitals' : IDL.Vec(Hospital),
          'services' : IDL.Vec(TourismService),
        }),
      ],
      ['query'],
    ),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getAllNgos' : IDL.Func([], [IDL.Vec(Ngo)], ['query']),
  'getAllRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
  'getAllTourismServices' : IDL.Func([], [IDL.Vec(TourismService)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthRecord' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
  'getHealthcareProfessionalById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthcareProfessional)],
      ['query'],
    ),
  'getHealthcareProfessionalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthcareProfessional)],
      ['query'],
    ),
  'getHealthcareProfessionalsByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthcareProfessional)],
      ['query'],
    ),
  'getHospitalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getLuxuryDebtApplications' : IDL.Func(
      [],
      [IDL.Vec(LuxuryDebtService)],
      ['query'],
    ),
  'getMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
  'getNgosByFocusArea' : IDL.Func([IDL.Text], [IDL.Vec(Ngo)], ['query']),
  'getPendingAmbulanceRequests' : IDL.Func(
      [],
      [IDL.Vec(AmbulanceRequest)],
      ['query'],
    ),
  'getPendingHealthcareProfessionalRequests' : IDL.Func(
      [],
      [IDL.Vec(HealthcareProfessionalRequest)],
      ['query'],
    ),
  'getPendingNgoRequests' : IDL.Func([], [IDL.Vec(NgoRequest)], ['query']),
  'getPendingVendorRequests' : IDL.Func(
      [],
      [IDL.Vec(VendorRequest)],
      ['query'],
    ),
  'getRecord' : IDL.Func([IDL.Text], [MedicalRecord], ['query']),
  'getResearchProject' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ResearchProject)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectAmbulance' : IDL.Func([IDL.Text], [], []),
  'rejectHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
  'rejectNgo' : IDL.Func([IDL.Text], [], []),
  'rejectVendor' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchRecords' : IDL.Func(
      [RecordFilter],
      [IDL.Vec(MedicalRecord)],
      ['query'],
    ),
  'searchResearchProjects' : IDL.Func(
      [ResearchFilter],
      [IDL.Vec(ResearchProject)],
      ['query'],
    ),
  'submitAmbulanceRegistration' : IDL.Func([AmbulanceRequest], [], []),
  'submitHealthcareProfessionalRegistration' : IDL.Func(
      [HealthcareProfessionalRequest],
      [],
      [],
    ),
  'submitNgoRegistration' : IDL.Func([NgoRequest], [], []),
  'submitVendorRegistration' : IDL.Func([VendorRequest], [], []),
  'updateRecord' : IDL.Func([MedicalRecord], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Location = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const Ngo = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'focusArea' : IDL.Text,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'registrationNo' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const TourismService = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'provider' : IDL.Text,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : Location,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const LuxuryDebtService = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'applicantName' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'amountRequested' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'contact' : ContactInfo,
    'radiologyCriteria' : IDL.Text,
    'name' : IDL.Text,
    'phisoCourses' : IDL.Vec(IDL.Text),
    'accreditation' : IDL.Text,
    'phisoPractices' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MedicalRecord = IDL.Record({
    'documents' : IDL.Vec(ExternalBlob),
    'patientId' : IDL.Text,
    'treatment' : IDL.Text,
    'diagnosis' : IDL.Text,
    'patientName' : IDL.Text,
    'recordId' : IDL.Text,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Text,
    'documents' : IDL.Vec(ExternalBlob),
    'labResults' : IDL.Vec(MedicalRecord),
    'userId' : IDL.Text,
    'imagingStudies' : IDL.Vec(ExternalBlob),
    'medications' : IDL.Vec(IDL.Text),
    'medicalHistory' : IDL.Vec(IDL.Text),
    'personalInfo' : IDL.Record({
      'dob' : IDL.Text,
      'bloodType' : IDL.Text,
      'name' : IDL.Text,
      'gender' : IDL.Text,
    }),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const ResearchProject = IDL.Record({
    'title' : IDL.Text,
    'researchers' : IDL.Vec(IDL.Text),
    'institution' : IDL.Text,
    'dataFiles' : IDL.Vec(ExternalBlob),
    'ethicsApproval' : IDL.Bool,
    'fundingSource' : IDL.Text,
    'projectId' : IDL.Text,
    'abstract' : IDL.Text,
  });
  const HealthcareProfessional = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'experience' : IDL.Nat,
    'credentials' : IDL.Vec(ExternalBlob),
    'specialties' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'professionalProfile' : IDL.Opt(HealthcareProfessional),
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AmbulanceRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'location' : Location,
  });
  const HealthcareProfessionalRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'experience' : IDL.Nat,
    'credentials' : IDL.Vec(ExternalBlob),
    'specialties' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const NgoRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'focusArea' : IDL.Text,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'registrationNo' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const VendorRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const RecordFilter = IDL.Record({
    'patientId' : IDL.Opt(IDL.Text),
    'diagnosis' : IDL.Opt(IDL.Text),
    'dateRange' : IDL.Opt(
      IDL.Record({ 'endDate' : IDL.Text, 'startDate' : IDL.Text })
    ),
  });
  const ResearchFilter = IDL.Record({
    'institution' : IDL.Opt(IDL.Text),
    'ethicsApproval' : IDL.Opt(IDL.Bool),
    'keyword' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCorporateHealthcareServices' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addNgo' : IDL.Func([Ngo], [], []),
    'addTourismService' : IDL.Func([TourismService], [], []),
    'addVendor' : IDL.Func([Vendor], [], []),
    'applyForLuxuryDebt' : IDL.Func([LuxuryDebtService], [], []),
    'approveAmbulance' : IDL.Func([IDL.Text], [], []),
    'approveHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
    'approveNgo' : IDL.Func([IDL.Text], [], []),
    'approveVendor' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCorporateHealthcare' : IDL.Func([Hospital], [], []),
    'createHealthRecord' : IDL.Func([HealthRecord], [], []),
    'createRecord' : IDL.Func([MedicalRecord], [], []),
    'createResearchProject' : IDL.Func([ResearchProject], [], []),
    'deleteRecord' : IDL.Func([IDL.Text], [], []),
    'filterDataByLocation' : IDL.Func(
        [Location],
        [
          IDL.Record({
            'professionals' : IDL.Vec(HealthcareProfessional),
            'vendors' : IDL.Vec(Vendor),
            'ngos' : IDL.Vec(Ngo),
            'hospitals' : IDL.Vec(Hospital),
            'services' : IDL.Vec(TourismService),
          }),
        ],
        ['query'],
      ),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getAllNgos' : IDL.Func([], [IDL.Vec(Ngo)], ['query']),
    'getAllRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
    'getAllTourismServices' : IDL.Func(
        [],
        [IDL.Vec(TourismService)],
        ['query'],
      ),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthRecord' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
    'getHealthcareProfessionalById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthcareProfessional)],
        ['query'],
      ),
    'getHealthcareProfessionalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthcareProfessional)],
        ['query'],
      ),
    'getHealthcareProfessionalsByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthcareProfessional)],
        ['query'],
      ),
    'getHospitalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getLuxuryDebtApplications' : IDL.Func(
        [],
        [IDL.Vec(LuxuryDebtService)],
        ['query'],
      ),
    'getMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
    'getNgosByFocusArea' : IDL.Func([IDL.Text], [IDL.Vec(Ngo)], ['query']),
    'getPendingAmbulanceRequests' : IDL.Func(
        [],
        [IDL.Vec(AmbulanceRequest)],
        ['query'],
      ),
    'getPendingHealthcareProfessionalRequests' : IDL.Func(
        [],
        [IDL.Vec(HealthcareProfessionalRequest)],
        ['query'],
      ),
    'getPendingNgoRequests' : IDL.Func([], [IDL.Vec(NgoRequest)], ['query']),
    'getPendingVendorRequests' : IDL.Func(
        [],
        [IDL.Vec(VendorRequest)],
        ['query'],
      ),
    'getRecord' : IDL.Func([IDL.Text], [MedicalRecord], ['query']),
    'getResearchProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ResearchProject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectAmbulance' : IDL.Func([IDL.Text], [], []),
    'rejectHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
    'rejectNgo' : IDL.Func([IDL.Text], [], []),
    'rejectVendor' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchRecords' : IDL.Func(
        [RecordFilter],
        [IDL.Vec(MedicalRecord)],
        ['query'],
      ),
    'searchResearchProjects' : IDL.Func(
        [ResearchFilter],
        [IDL.Vec(ResearchProject)],
        ['query'],
      ),
    'submitAmbulanceRegistration' : IDL.Func([AmbulanceRequest], [], []),
    'submitHealthcareProfessionalRegistration' : IDL.Func(
        [HealthcareProfessionalRequest],
        [],
        [],
      ),
    'submitNgoRegistration' : IDL.Func([NgoRequest], [], []),
    'submitVendorRegistration' : IDL.Func([VendorRequest], [], []),
    'updateRecord' : IDL.Func([MedicalRecord], [], []),
  });
};

export const init = ({ IDL }) => { return []; };