/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AmbulanceRequest {
  'id' : string,
  'status' : RequestStatus,
  'requester' : Principal,
  'contact' : ContactInfo,
  'name' : string,
  'location' : Location,
}
export interface BlogArticle {
  'metaDescription' : string,
  'title' : string,
  'content' : string,
  'publishDate' : Time,
  'published' : boolean,
  'slug' : string,
  'tags' : Array<string>,
  'author' : string,
  'metaTitle' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactInfo {
  'email' : string,
  'website' : string,
  'address' : string,
  'phone' : string,
}
export interface DemoBookingRequest {
  'status' : DemoBookingStatus,
  'city' : string,
  'name' : string,
  'designation' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'hospitalName' : string,
  'mobile' : string,
}
export type DemoBookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'contacted' : null };
export interface DocumentMetadata {
  'status' : string,
  'blob' : ExternalBlob,
  'filename' : string,
  'filetype' : string,
  'uploader' : Principal,
  'uploadTime' : bigint,
}
export interface DocumentPhase { 'name' : string, 'phaseNumber' : bigint }
export interface DocumentSection {
  'paragraphs' : Array<string>,
  'heading' : string,
  'lists' : Array<ListContent>,
  'tables' : Array<TableContent>,
}
export interface DocumentType { 'name' : string, 'description' : string }
export type ExternalBlob = Uint8Array;
export interface HealthRecord {
  'id' : string,
  'documents' : Array<ExternalBlob>,
  'labResults' : Array<MedicalRecord>,
  'userId' : string,
  'imagingStudies' : Array<ExternalBlob>,
  'medications' : Array<string>,
  'medicalHistory' : Array<string>,
  'personalInfo' : {
    'dob' : string,
    'bloodType' : string,
    'name' : string,
    'gender' : string,
  },
  'allergies' : Array<string>,
}
export interface HealthcareProfessional {
  'id' : string,
  'verified' : boolean,
  'contact' : ContactInfo,
  'name' : string,
  'role' : string,
  'experience' : bigint,
  'credentials' : Array<ExternalBlob>,
  'specialties' : Array<string>,
  'location' : Location,
}
export interface HealthcareProfessionalRequest {
  'id' : string,
  'status' : RequestStatus,
  'requester' : Principal,
  'contact' : ContactInfo,
  'name' : string,
  'role' : string,
  'experience' : bigint,
  'credentials' : Array<ExternalBlob>,
  'specialties' : Array<string>,
  'location' : Location,
}
export interface Hospital {
  'id' : string,
  'contact' : ContactInfo,
  'radiologyCriteria' : string,
  'name' : string,
  'phisoCourses' : Array<string>,
  'accreditation' : string,
  'phisoPractices' : Array<string>,
  'address' : string,
  'location' : Location,
  'services' : Array<string>,
}
export interface ListContent { 'items' : Array<string> }
export interface Location {
  'country' : string,
  'city' : string,
  'state' : string,
}
export interface LuxuryDebtService {
  'id' : string,
  'serviceType' : string,
  'applicantName' : string,
  'approvalStatus' : string,
  'amountRequested' : bigint,
}
export interface MedicalRecord {
  'documents' : Array<ExternalBlob>,
  'patientId' : string,
  'treatment' : string,
  'diagnosis' : string,
  'patientName' : string,
  'recordId' : string,
}
export interface Ngo {
  'id' : string,
  'verified' : boolean,
  'focusArea' : string,
  'contact' : ContactInfo,
  'name' : string,
  'registrationNo' : string,
  'location' : Location,
  'services' : Array<string>,
}
export interface NgoRequest {
  'id' : string,
  'status' : RequestStatus,
  'requester' : Principal,
  'focusArea' : string,
  'contact' : ContactInfo,
  'name' : string,
  'registrationNo' : string,
  'location' : Location,
  'services' : Array<string>,
}
export interface PatientJourneySampleDocument {
  'id' : string,
  'hospital' : Principal,
  'verified' : boolean,
  'documentType' : DocumentType,
  'blob' : ExternalBlob,
  'filename' : string,
  'hospitalId' : string,
  'phase' : DocumentPhase,
  'uploadTime' : Time,
}
export interface ProcessedDocument {
  'metadata' : DocumentMetadata,
  'summary' : string,
  'documentId' : string,
  'sections' : Array<DocumentSection>,
}
export interface RecordFilter {
  'patientId' : [] | [string],
  'diagnosis' : [] | [string],
  'dateRange' : [] | [{ 'endDate' : string, 'startDate' : string }],
}
export type RequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ResearchFilter {
  'institution' : [] | [string],
  'ethicsApproval' : [] | [boolean],
  'keyword' : [] | [string],
}
export interface ResearchProject {
  'title' : string,
  'researchers' : Array<string>,
  'institution' : string,
  'dataFiles' : Array<ExternalBlob>,
  'ethicsApproval' : boolean,
  'fundingSource' : string,
  'projectId' : string,
  'abstract' : string,
}
export interface TableContent {
  'rows' : Array<Array<string>>,
  'headers' : Array<string>,
}
export type Time = bigint;
export interface TourismService {
  'id' : string,
  'verified' : boolean,
  'provider' : string,
  'cost' : bigint,
  'name' : string,
  'description' : string,
  'category' : string,
  'location' : Location,
}
export interface UserProfile {
  'userType' : string,
  'professionalProfile' : [] | [HealthcareProfessional],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vendor {
  'id' : string,
  'verified' : boolean,
  'contact' : ContactInfo,
  'name' : string,
  'category' : string,
  'products' : Array<string>,
  'location' : Location,
}
export interface VendorRequest {
  'id' : string,
  'status' : RequestStatus,
  'requester' : Principal,
  'contact' : ContactInfo,
  'name' : string,
  'category' : string,
  'products' : Array<string>,
  'location' : Location,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCorporateHealthcareServices' : ActorMethod<
    [string, Array<string>],
    undefined
  >,
  'addNgo' : ActorMethod<[Ngo], undefined>,
  'addTourismService' : ActorMethod<[TourismService], undefined>,
  'addVendor' : ActorMethod<[Vendor], undefined>,
  'applyForLuxuryDebt' : ActorMethod<[LuxuryDebtService], undefined>,
  'approveAmbulance' : ActorMethod<[string], undefined>,
  'approveHealthcareProfessional' : ActorMethod<[string], undefined>,
  'approveNgo' : ActorMethod<[string], undefined>,
  'approveVendor' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBlogArticle' : ActorMethod<[BlogArticle], undefined>,
  'createCorporateHealthcare' : ActorMethod<[Hospital], undefined>,
  'createHealthRecord' : ActorMethod<[HealthRecord], undefined>,
  'createRecord' : ActorMethod<[MedicalRecord], undefined>,
  'createResearchProject' : ActorMethod<[ResearchProject], undefined>,
  'deleteRecord' : ActorMethod<[string], undefined>,
  'filterDataByLocation' : ActorMethod<
    [Location],
    {
      'professionals' : Array<HealthcareProfessional>,
      'vendors' : Array<Vendor>,
      'ngos' : Array<Ngo>,
      'hospitals' : Array<Hospital>,
      'services' : Array<TourismService>,
    }
  >,
  'getAllBlogArticles' : ActorMethod<[], Array<BlogArticle>>,
  'getAllDemoBookingRequests' : ActorMethod<
    [[] | [DemoBookingStatus]],
    Array<DemoBookingRequest>
  >,
  'getAllHospitals' : ActorMethod<[], Array<Hospital>>,
  'getAllNgos' : ActorMethod<[], Array<Ngo>>,
  'getAllPatientJourneySampleDocuments' : ActorMethod<
    [],
    Array<PatientJourneySampleDocument>
  >,
  'getAllRecords' : ActorMethod<[], Array<MedicalRecord>>,
  'getAllTourismServices' : ActorMethod<[], Array<TourismService>>,
  'getAllVendors' : ActorMethod<[], Array<Vendor>>,
  'getApprovedStakeholderLocations' : ActorMethod<[], Array<Location>>,
  'getBlogArticle' : ActorMethod<[string], [] | [BlogArticle]>,
  'getBlogArticlesByCategory' : ActorMethod<[string], Array<BlogArticle>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getHealthRecord' : ActorMethod<[string], HealthRecord>,
  'getHealthcareProfessionalById' : ActorMethod<
    [string],
    [] | [HealthcareProfessional]
  >,
  'getHealthcareProfessionalsByLocation' : ActorMethod<
    [string],
    Array<HealthcareProfessional>
  >,
  'getHealthcareProfessionalsByRole' : ActorMethod<
    [string],
    Array<HealthcareProfessional>
  >,
  'getHospitalPatientJourneySampleDocuments' : ActorMethod<
    [string, [] | [bigint]],
    Array<PatientJourneySampleDocument>
  >,
  'getHospitalsByLocation' : ActorMethod<[string], Array<Hospital>>,
  'getLuxuryDebtApplications' : ActorMethod<[], Array<LuxuryDebtService>>,
  'getMyRecords' : ActorMethod<[], Array<MedicalRecord>>,
  'getNgosByFocusArea' : ActorMethod<[string], Array<Ngo>>,
  'getPendingAmbulanceRequests' : ActorMethod<[], Array<AmbulanceRequest>>,
  'getPendingHealthcareProfessionalRequests' : ActorMethod<
    [],
    Array<HealthcareProfessionalRequest>
  >,
  'getPendingNgoRequests' : ActorMethod<[], Array<NgoRequest>>,
  'getPendingVendorRequests' : ActorMethod<[], Array<VendorRequest>>,
  'getProcessedDocument' : ActorMethod<[string], [] | [ProcessedDocument]>,
  'getRecord' : ActorMethod<[string], MedicalRecord>,
  'getResearchProject' : ActorMethod<[string], [] | [ResearchProject]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSampleData' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'processDocument' : ActorMethod<
    [string, Array<DocumentSection>, string],
    undefined
  >,
  'rejectAmbulance' : ActorMethod<[string], undefined>,
  'rejectHealthcareProfessional' : ActorMethod<[string], undefined>,
  'rejectNgo' : ActorMethod<[string], undefined>,
  'rejectVendor' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDemoBookingRequest' : ActorMethod<
    [
      {
        'city' : string,
        'name' : string,
        'designation' : string,
        'email' : string,
        'message' : string,
        'hospitalName' : string,
        'mobile' : string,
      },
    ],
    undefined
  >,
  'searchBlogArticles' : ActorMethod<[string], Array<BlogArticle>>,
  'searchRecords' : ActorMethod<[RecordFilter], Array<MedicalRecord>>,
  'searchResearchProjects' : ActorMethod<
    [ResearchFilter],
    Array<ResearchProject>
  >,
  'submitAmbulanceRegistration' : ActorMethod<[AmbulanceRequest], undefined>,
  'submitHealthcareProfessionalRegistration' : ActorMethod<
    [HealthcareProfessionalRequest],
    undefined
  >,
  'submitNgoRegistration' : ActorMethod<[NgoRequest], undefined>,
  'submitVendorRegistration' : ActorMethod<[VendorRequest], undefined>,
  'updateBlogArticle' : ActorMethod<[string, BlogArticle], undefined>,
  'updateRecord' : ActorMethod<[MedicalRecord], undefined>,
  'uploadDocument' : ActorMethod<
    [string, string, string, ExternalBlob],
    undefined
  >,
  'uploadPatientJourneySampleDocument' : ActorMethod<
    [string, DocumentPhase, DocumentType, string, string, ExternalBlob],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];