/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ContactInfo = IDL.Record({
  'email' : IDL.Text,
  'website' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Location = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
});
export const Ngo = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'focusArea' : IDL.Text,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'registrationNo' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const TourismService = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'provider' : IDL.Text,
  'cost' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'location' : Location,
});
export const Vendor = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const LuxuryDebtService = IDL.Record({
  'id' : IDL.Text,
  'serviceType' : IDL.Text,
  'applicantName' : IDL.Text,
  'approvalStatus' : IDL.Text,
  'amountRequested' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogArticle = IDL.Record({
  'metaDescription' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'publishDate' : Time,
  'published' : IDL.Bool,
  'slug' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'author' : IDL.Text,
  'metaTitle' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const Hospital = IDL.Record({
  'id' : IDL.Text,
  'contact' : ContactInfo,
  'radiologyCriteria' : IDL.Text,
  'name' : IDL.Text,
  'phisoCourses' : IDL.Vec(IDL.Text),
  'accreditation' : IDL.Text,
  'phisoPractices' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const MedicalRecord = IDL.Record({
  'documents' : IDL.Vec(ExternalBlob),
  'patientId' : IDL.Text,
  'treatment' : IDL.Text,
  'diagnosis' : IDL.Text,
  'patientName' : IDL.Text,
  'recordId' : IDL.Text,
});
export const HealthRecord = IDL.Record({
  'id' : IDL.Text,
  'documents' : IDL.Vec(ExternalBlob),
  'labResults' : IDL.Vec(MedicalRecord),
  'userId' : IDL.Text,
  'imagingStudies' : IDL.Vec(ExternalBlob),
  'medications' : IDL.Vec(IDL.Text),
  'medicalHistory' : IDL.Vec(IDL.Text),
  'personalInfo' : IDL.Record({
    'dob' : IDL.Text,
    'bloodType' : IDL.Text,
    'name' : IDL.Text,
    'gender' : IDL.Text,
  }),
  'allergies' : IDL.Vec(IDL.Text),
});
export const ResearchProject = IDL.Record({
  'title' : IDL.Text,
  'researchers' : IDL.Vec(IDL.Text),
  'institution' : IDL.Text,
  'dataFiles' : IDL.Vec(ExternalBlob),
  'ethicsApproval' : IDL.Bool,
  'fundingSource' : IDL.Text,
  'projectId' : IDL.Text,
  'abstract' : IDL.Text,
});
export const HealthcareProfessional = IDL.Record({
  'id' : IDL.Text,
  'verified' : IDL.Bool,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'experience' : IDL.Nat,
  'credentials' : IDL.Vec(ExternalBlob),
  'specialties' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const DemoBookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'contacted' : IDL.Null,
});
export const DemoBookingRequest = IDL.Record({
  'status' : DemoBookingStatus,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'designation' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'hospitalName' : IDL.Text,
  'mobile' : IDL.Text,
});
export const DocumentType = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const DocumentPhase = IDL.Record({
  'name' : IDL.Text,
  'phaseNumber' : IDL.Nat,
});
export const PatientJourneySampleDocument = IDL.Record({
  'id' : IDL.Text,
  'hospital' : IDL.Principal,
  'verified' : IDL.Bool,
  'documentType' : DocumentType,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'hospitalId' : IDL.Text,
  'phase' : DocumentPhase,
  'uploadTime' : Time,
});
export const UserProfile = IDL.Record({
  'userType' : IDL.Text,
  'professionalProfile' : IDL.Opt(HealthcareProfessional),
});
export const RequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const AmbulanceRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'location' : Location,
});
export const HealthcareProfessionalRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'experience' : IDL.Nat,
  'credentials' : IDL.Vec(ExternalBlob),
  'specialties' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const NgoRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'focusArea' : IDL.Text,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'registrationNo' : IDL.Text,
  'location' : Location,
  'services' : IDL.Vec(IDL.Text),
});
export const VendorRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'requester' : IDL.Principal,
  'contact' : ContactInfo,
  'name' : IDL.Text,
  'category' : IDL.Text,
  'products' : IDL.Vec(IDL.Text),
  'location' : Location,
});
export const DocumentMetadata = IDL.Record({
  'status' : IDL.Text,
  'blob' : ExternalBlob,
  'filename' : IDL.Text,
  'filetype' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadTime' : IDL.Nat,
});
export const ListContent = IDL.Record({ 'items' : IDL.Vec(IDL.Text) });
export const TableContent = IDL.Record({
  'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
  'headers' : IDL.Vec(IDL.Text),
});
export const DocumentSection = IDL.Record({
  'paragraphs' : IDL.Vec(IDL.Text),
  'heading' : IDL.Text,
  'lists' : IDL.Vec(ListContent),
  'tables' : IDL.Vec(TableContent),
});
export const ProcessedDocument = IDL.Record({
  'metadata' : DocumentMetadata,
  'summary' : IDL.Text,
  'documentId' : IDL.Text,
  'sections' : IDL.Vec(DocumentSection),
});
export const RecordFilter = IDL.Record({
  'patientId' : IDL.Opt(IDL.Text),
  'diagnosis' : IDL.Opt(IDL.Text),
  'dateRange' : IDL.Opt(
    IDL.Record({ 'endDate' : IDL.Text, 'startDate' : IDL.Text })
  ),
});
export const ResearchFilter = IDL.Record({
  'institution' : IDL.Opt(IDL.Text),
  'ethicsApproval' : IDL.Opt(IDL.Bool),
  'keyword' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCorporateHealthcareServices' : IDL.Func(
      [IDL.Text, IDL.Vec(IDL.Text)],
      [],
      [],
    ),
  'addNgo' : IDL.Func([Ngo], [], []),
  'addTourismService' : IDL.Func([TourismService], [], []),
  'addVendor' : IDL.Func([Vendor], [], []),
  'applyForLuxuryDebt' : IDL.Func([LuxuryDebtService], [], []),
  'approveAmbulance' : IDL.Func([IDL.Text], [], []),
  'approveHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
  'approveNgo' : IDL.Func([IDL.Text], [], []),
  'approveVendor' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogArticle' : IDL.Func([BlogArticle], [], []),
  'createCorporateHealthcare' : IDL.Func([Hospital], [], []),
  'createHealthRecord' : IDL.Func([HealthRecord], [], []),
  'createRecord' : IDL.Func([MedicalRecord], [], []),
  'createResearchProject' : IDL.Func([ResearchProject], [], []),
  'deleteRecord' : IDL.Func([IDL.Text], [], []),
  'filterDataByLocation' : IDL.Func(
      [Location],
      [
        IDL.Record({
          'professionals' : IDL.Vec(HealthcareProfessional),
          'vendors' : IDL.Vec(Vendor),
          'ngos' : IDL.Vec(Ngo),
          'hospitals' : IDL.Vec(Hospital),
          'services' : IDL.Vec(TourismService),
        }),
      ],
      ['query'],
    ),
  'getAllBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
  'getAllDemoBookingRequests' : IDL.Func(
      [IDL.Opt(DemoBookingStatus)],
      [IDL.Vec(DemoBookingRequest)],
      ['query'],
    ),
  'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'getAllNgos' : IDL.Func([], [IDL.Vec(Ngo)], ['query']),
  'getAllPatientJourneySampleDocuments' : IDL.Func(
      [],
      [IDL.Vec(PatientJourneySampleDocument)],
      ['query'],
    ),
  'getAllRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
  'getAllTourismServices' : IDL.Func([], [IDL.Vec(TourismService)], ['query']),
  'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
  'getApprovedStakeholderLocations' : IDL.Func(
      [],
      [IDL.Vec(Location)],
      ['query'],
    ),
  'getBlogArticle' : IDL.Func([IDL.Text], [IDL.Opt(BlogArticle)], ['query']),
  'getBlogArticlesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogArticle)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getHealthRecord' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
  'getHealthcareProfessionalById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(HealthcareProfessional)],
      ['query'],
    ),
  'getHealthcareProfessionalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthcareProfessional)],
      ['query'],
    ),
  'getHealthcareProfessionalsByRole' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(HealthcareProfessional)],
      ['query'],
    ),
  'getHospitalPatientJourneySampleDocuments' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat)],
      [IDL.Vec(PatientJourneySampleDocument)],
      ['query'],
    ),
  'getHospitalsByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Hospital)],
      ['query'],
    ),
  'getLuxuryDebtApplications' : IDL.Func(
      [],
      [IDL.Vec(LuxuryDebtService)],
      ['query'],
    ),
  'getMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
  'getNgosByFocusArea' : IDL.Func([IDL.Text], [IDL.Vec(Ngo)], ['query']),
  'getPendingAmbulanceRequests' : IDL.Func(
      [],
      [IDL.Vec(AmbulanceRequest)],
      ['query'],
    ),
  'getPendingHealthcareProfessionalRequests' : IDL.Func(
      [],
      [IDL.Vec(HealthcareProfessionalRequest)],
      ['query'],
    ),
  'getPendingNgoRequests' : IDL.Func([], [IDL.Vec(NgoRequest)], ['query']),
  'getPendingVendorRequests' : IDL.Func(
      [],
      [IDL.Vec(VendorRequest)],
      ['query'],
    ),
  'getProcessedDocument' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ProcessedDocument)],
      ['query'],
    ),
  'getRecord' : IDL.Func([IDL.Text], [MedicalRecord], ['query']),
  'getResearchProject' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ResearchProject)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSampleData' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'processDocument' : IDL.Func(
      [IDL.Text, IDL.Vec(DocumentSection), IDL.Text],
      [],
      [],
    ),
  'rejectAmbulance' : IDL.Func([IDL.Text], [], []),
  'rejectHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
  'rejectNgo' : IDL.Func([IDL.Text], [], []),
  'rejectVendor' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDemoBookingRequest' : IDL.Func(
      [
        IDL.Record({
          'city' : IDL.Text,
          'name' : IDL.Text,
          'designation' : IDL.Text,
          'email' : IDL.Text,
          'message' : IDL.Text,
          'hospitalName' : IDL.Text,
          'mobile' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'searchBlogArticles' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogArticle)],
      ['query'],
    ),
  'searchRecords' : IDL.Func(
      [RecordFilter],
      [IDL.Vec(MedicalRecord)],
      ['query'],
    ),
  'searchResearchProjects' : IDL.Func(
      [ResearchFilter],
      [IDL.Vec(ResearchProject)],
      ['query'],
    ),
  'submitAmbulanceRegistration' : IDL.Func([AmbulanceRequest], [], []),
  'submitHealthcareProfessionalRegistration' : IDL.Func(
      [HealthcareProfessionalRequest],
      [],
      [],
    ),
  'submitNgoRegistration' : IDL.Func([NgoRequest], [], []),
  'submitVendorRegistration' : IDL.Func([VendorRequest], [], []),
  'updateBlogArticle' : IDL.Func([IDL.Text, BlogArticle], [], []),
  'updateRecord' : IDL.Func([MedicalRecord], [], []),
  'uploadDocument' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
  'uploadPatientJourneySampleDocument' : IDL.Func(
      [IDL.Text, DocumentPhase, DocumentType, IDL.Text, IDL.Text, ExternalBlob],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ContactInfo = IDL.Record({
    'email' : IDL.Text,
    'website' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Location = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
  });
  const Ngo = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'focusArea' : IDL.Text,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'registrationNo' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const TourismService = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'provider' : IDL.Text,
    'cost' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'location' : Location,
  });
  const Vendor = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const LuxuryDebtService = IDL.Record({
    'id' : IDL.Text,
    'serviceType' : IDL.Text,
    'applicantName' : IDL.Text,
    'approvalStatus' : IDL.Text,
    'amountRequested' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogArticle = IDL.Record({
    'metaDescription' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'publishDate' : Time,
    'published' : IDL.Bool,
    'slug' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'author' : IDL.Text,
    'metaTitle' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const Hospital = IDL.Record({
    'id' : IDL.Text,
    'contact' : ContactInfo,
    'radiologyCriteria' : IDL.Text,
    'name' : IDL.Text,
    'phisoCourses' : IDL.Vec(IDL.Text),
    'accreditation' : IDL.Text,
    'phisoPractices' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const MedicalRecord = IDL.Record({
    'documents' : IDL.Vec(ExternalBlob),
    'patientId' : IDL.Text,
    'treatment' : IDL.Text,
    'diagnosis' : IDL.Text,
    'patientName' : IDL.Text,
    'recordId' : IDL.Text,
  });
  const HealthRecord = IDL.Record({
    'id' : IDL.Text,
    'documents' : IDL.Vec(ExternalBlob),
    'labResults' : IDL.Vec(MedicalRecord),
    'userId' : IDL.Text,
    'imagingStudies' : IDL.Vec(ExternalBlob),
    'medications' : IDL.Vec(IDL.Text),
    'medicalHistory' : IDL.Vec(IDL.Text),
    'personalInfo' : IDL.Record({
      'dob' : IDL.Text,
      'bloodType' : IDL.Text,
      'name' : IDL.Text,
      'gender' : IDL.Text,
    }),
    'allergies' : IDL.Vec(IDL.Text),
  });
  const ResearchProject = IDL.Record({
    'title' : IDL.Text,
    'researchers' : IDL.Vec(IDL.Text),
    'institution' : IDL.Text,
    'dataFiles' : IDL.Vec(ExternalBlob),
    'ethicsApproval' : IDL.Bool,
    'fundingSource' : IDL.Text,
    'projectId' : IDL.Text,
    'abstract' : IDL.Text,
  });
  const HealthcareProfessional = IDL.Record({
    'id' : IDL.Text,
    'verified' : IDL.Bool,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'experience' : IDL.Nat,
    'credentials' : IDL.Vec(ExternalBlob),
    'specialties' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const DemoBookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const DemoBookingRequest = IDL.Record({
    'status' : DemoBookingStatus,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'designation' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'hospitalName' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const DocumentType = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const DocumentPhase = IDL.Record({
    'name' : IDL.Text,
    'phaseNumber' : IDL.Nat,
  });
  const PatientJourneySampleDocument = IDL.Record({
    'id' : IDL.Text,
    'hospital' : IDL.Principal,
    'verified' : IDL.Bool,
    'documentType' : DocumentType,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'hospitalId' : IDL.Text,
    'phase' : DocumentPhase,
    'uploadTime' : Time,
  });
  const UserProfile = IDL.Record({
    'userType' : IDL.Text,
    'professionalProfile' : IDL.Opt(HealthcareProfessional),
  });
  const RequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const AmbulanceRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'location' : Location,
  });
  const HealthcareProfessionalRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'experience' : IDL.Nat,
    'credentials' : IDL.Vec(ExternalBlob),
    'specialties' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const NgoRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'focusArea' : IDL.Text,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'registrationNo' : IDL.Text,
    'location' : Location,
    'services' : IDL.Vec(IDL.Text),
  });
  const VendorRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'requester' : IDL.Principal,
    'contact' : ContactInfo,
    'name' : IDL.Text,
    'category' : IDL.Text,
    'products' : IDL.Vec(IDL.Text),
    'location' : Location,
  });
  const DocumentMetadata = IDL.Record({
    'status' : IDL.Text,
    'blob' : ExternalBlob,
    'filename' : IDL.Text,
    'filetype' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadTime' : IDL.Nat,
  });
  const ListContent = IDL.Record({ 'items' : IDL.Vec(IDL.Text) });
  const TableContent = IDL.Record({
    'rows' : IDL.Vec(IDL.Vec(IDL.Text)),
    'headers' : IDL.Vec(IDL.Text),
  });
  const DocumentSection = IDL.Record({
    'paragraphs' : IDL.Vec(IDL.Text),
    'heading' : IDL.Text,
    'lists' : IDL.Vec(ListContent),
    'tables' : IDL.Vec(TableContent),
  });
  const ProcessedDocument = IDL.Record({
    'metadata' : DocumentMetadata,
    'summary' : IDL.Text,
    'documentId' : IDL.Text,
    'sections' : IDL.Vec(DocumentSection),
  });
  const RecordFilter = IDL.Record({
    'patientId' : IDL.Opt(IDL.Text),
    'diagnosis' : IDL.Opt(IDL.Text),
    'dateRange' : IDL.Opt(
      IDL.Record({ 'endDate' : IDL.Text, 'startDate' : IDL.Text })
    ),
  });
  const ResearchFilter = IDL.Record({
    'institution' : IDL.Opt(IDL.Text),
    'ethicsApproval' : IDL.Opt(IDL.Bool),
    'keyword' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCorporateHealthcareServices' : IDL.Func(
        [IDL.Text, IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    'addNgo' : IDL.Func([Ngo], [], []),
    'addTourismService' : IDL.Func([TourismService], [], []),
    'addVendor' : IDL.Func([Vendor], [], []),
    'applyForLuxuryDebt' : IDL.Func([LuxuryDebtService], [], []),
    'approveAmbulance' : IDL.Func([IDL.Text], [], []),
    'approveHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
    'approveNgo' : IDL.Func([IDL.Text], [], []),
    'approveVendor' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogArticle' : IDL.Func([BlogArticle], [], []),
    'createCorporateHealthcare' : IDL.Func([Hospital], [], []),
    'createHealthRecord' : IDL.Func([HealthRecord], [], []),
    'createRecord' : IDL.Func([MedicalRecord], [], []),
    'createResearchProject' : IDL.Func([ResearchProject], [], []),
    'deleteRecord' : IDL.Func([IDL.Text], [], []),
    'filterDataByLocation' : IDL.Func(
        [Location],
        [
          IDL.Record({
            'professionals' : IDL.Vec(HealthcareProfessional),
            'vendors' : IDL.Vec(Vendor),
            'ngos' : IDL.Vec(Ngo),
            'hospitals' : IDL.Vec(Hospital),
            'services' : IDL.Vec(TourismService),
          }),
        ],
        ['query'],
      ),
    'getAllBlogArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
    'getAllDemoBookingRequests' : IDL.Func(
        [IDL.Opt(DemoBookingStatus)],
        [IDL.Vec(DemoBookingRequest)],
        ['query'],
      ),
    'getAllHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'getAllNgos' : IDL.Func([], [IDL.Vec(Ngo)], ['query']),
    'getAllPatientJourneySampleDocuments' : IDL.Func(
        [],
        [IDL.Vec(PatientJourneySampleDocument)],
        ['query'],
      ),
    'getAllRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
    'getAllTourismServices' : IDL.Func(
        [],
        [IDL.Vec(TourismService)],
        ['query'],
      ),
    'getAllVendors' : IDL.Func([], [IDL.Vec(Vendor)], ['query']),
    'getApprovedStakeholderLocations' : IDL.Func(
        [],
        [IDL.Vec(Location)],
        ['query'],
      ),
    'getBlogArticle' : IDL.Func([IDL.Text], [IDL.Opt(BlogArticle)], ['query']),
    'getBlogArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogArticle)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getHealthRecord' : IDL.Func([IDL.Text], [HealthRecord], ['query']),
    'getHealthcareProfessionalById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(HealthcareProfessional)],
        ['query'],
      ),
    'getHealthcareProfessionalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthcareProfessional)],
        ['query'],
      ),
    'getHealthcareProfessionalsByRole' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(HealthcareProfessional)],
        ['query'],
      ),
    'getHospitalPatientJourneySampleDocuments' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat)],
        [IDL.Vec(PatientJourneySampleDocument)],
        ['query'],
      ),
    'getHospitalsByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Hospital)],
        ['query'],
      ),
    'getLuxuryDebtApplications' : IDL.Func(
        [],
        [IDL.Vec(LuxuryDebtService)],
        ['query'],
      ),
    'getMyRecords' : IDL.Func([], [IDL.Vec(MedicalRecord)], ['query']),
    'getNgosByFocusArea' : IDL.Func([IDL.Text], [IDL.Vec(Ngo)], ['query']),
    'getPendingAmbulanceRequests' : IDL.Func(
        [],
        [IDL.Vec(AmbulanceRequest)],
        ['query'],
      ),
    'getPendingHealthcareProfessionalRequests' : IDL.Func(
        [],
        [IDL.Vec(HealthcareProfessionalRequest)],
        ['query'],
      ),
    'getPendingNgoRequests' : IDL.Func([], [IDL.Vec(NgoRequest)], ['query']),
    'getPendingVendorRequests' : IDL.Func(
        [],
        [IDL.Vec(VendorRequest)],
        ['query'],
      ),
    'getProcessedDocument' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ProcessedDocument)],
        ['query'],
      ),
    'getRecord' : IDL.Func([IDL.Text], [MedicalRecord], ['query']),
    'getResearchProject' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ResearchProject)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSampleData' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'processDocument' : IDL.Func(
        [IDL.Text, IDL.Vec(DocumentSection), IDL.Text],
        [],
        [],
      ),
    'rejectAmbulance' : IDL.Func([IDL.Text], [], []),
    'rejectHealthcareProfessional' : IDL.Func([IDL.Text], [], []),
    'rejectNgo' : IDL.Func([IDL.Text], [], []),
    'rejectVendor' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDemoBookingRequest' : IDL.Func(
        [
          IDL.Record({
            'city' : IDL.Text,
            'name' : IDL.Text,
            'designation' : IDL.Text,
            'email' : IDL.Text,
            'message' : IDL.Text,
            'hospitalName' : IDL.Text,
            'mobile' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'searchBlogArticles' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogArticle)],
        ['query'],
      ),
    'searchRecords' : IDL.Func(
        [RecordFilter],
        [IDL.Vec(MedicalRecord)],
        ['query'],
      ),
    'searchResearchProjects' : IDL.Func(
        [ResearchFilter],
        [IDL.Vec(ResearchProject)],
        ['query'],
      ),
    'submitAmbulanceRegistration' : IDL.Func([AmbulanceRequest], [], []),
    'submitHealthcareProfessionalRegistration' : IDL.Func(
        [HealthcareProfessionalRequest],
        [],
        [],
      ),
    'submitNgoRegistration' : IDL.Func([NgoRequest], [], []),
    'submitVendorRegistration' : IDL.Func([VendorRequest], [], []),
    'updateBlogArticle' : IDL.Func([IDL.Text, BlogArticle], [], []),
    'updateRecord' : IDL.Func([MedicalRecord], [], []),
    'uploadDocument' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob],
        [],
        [],
      ),
    'uploadPatientJourneySampleDocument' : IDL.Func(
        [
          IDL.Text,
          DocumentPhase,
          DocumentType,
          IDL.Text,
          IDL.Text,
          ExternalBlob,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };