/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Location {
    country: string;
    city: string;
    state: string;
}
export interface MedicalRecord {
    documents: Array<ExternalBlob>;
    patientId: string;
    treatment: string;
    diagnosis: string;
    patientName: string;
    recordId: string;
}
export interface RecordFilter {
    patientId?: string;
    diagnosis?: string;
    dateRange?: {
        endDate: string;
        startDate: string;
    };
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface HealthcareProfessional {
    id: string;
    verified: boolean;
    contact: ContactInfo;
    name: string;
    role: string;
    experience: bigint;
    credentials: Array<ExternalBlob>;
    specialties: Array<string>;
    location: Location;
}
export interface ContactInfo {
    email: string;
    website: string;
    address: string;
    phone: string;
}
export interface TourismService {
    id: string;
    verified: boolean;
    provider: string;
    cost: bigint;
    name: string;
    description: string;
    category: string;
    location: Location;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface HealthRecord {
    id: string;
    documents: Array<ExternalBlob>;
    labResults: Array<MedicalRecord>;
    userId: string;
    imagingStudies: Array<ExternalBlob>;
    medications: Array<string>;
    medicalHistory: Array<string>;
    personalInfo: {
        dob: string;
        bloodType: string;
        name: string;
        gender: string;
    };
    allergies: Array<string>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Ngo {
    id: string;
    verified: boolean;
    focusArea: string;
    contact: ContactInfo;
    name: string;
    registrationNo: string;
    location: Location;
    services: Array<string>;
}
export interface ResearchProject {
    title: string;
    researchers: Array<string>;
    institution: string;
    dataFiles: Array<ExternalBlob>;
    ethicsApproval: boolean;
    fundingSource: string;
    projectId: string;
    abstract: string;
}
export interface Hospital {
    id: string;
    contact: ContactInfo;
    radiologyCriteria: string;
    name: string;
    phisoCourses: Array<string>;
    accreditation: string;
    phisoPractices: Array<string>;
    address: string;
    location: Location;
    services: Array<string>;
}
export interface Vendor {
    id: string;
    verified: boolean;
    contact: ContactInfo;
    name: string;
    category: string;
    products: Array<string>;
    location: Location;
}
export interface LuxuryDebtService {
    id: string;
    serviceType: string;
    applicantName: string;
    approvalStatus: string;
    amountRequested: bigint;
}
export interface ResearchFilter {
    institution?: string;
    ethicsApproval?: boolean;
    keyword?: string;
}
export interface UserProfile {
    userType: string;
    professionalProfile?: HealthcareProfessional;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCorporateHealthcareServices(hospitalId: string, services: Array<string>): Promise<void>;
    addHealthcareProfessional(professional: HealthcareProfessional): Promise<void>;
    addNgo(ngo: Ngo): Promise<void>;
    addTourismService(service: TourismService): Promise<void>;
    addVendor(vendor: Vendor): Promise<void>;
    applyForLuxuryDebt(application: LuxuryDebtService): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCorporateHealthcare(hospital: Hospital): Promise<void>;
    createHealthRecord(record: HealthRecord): Promise<void>;
    createRecord(record: MedicalRecord): Promise<void>;
    createResearchProject(project: ResearchProject): Promise<void>;
    deleteRecord(recordId: string): Promise<void>;
    filterDataByLocation(location: Location): Promise<{
        professionals: Array<HealthcareProfessional>;
        vendors: Array<Vendor>;
        ngos: Array<Ngo>;
        hospitals: Array<Hospital>;
        services: Array<TourismService>;
    }>;
    getAllHospitals(): Promise<Array<Hospital>>;
    getAllNgos(): Promise<Array<Ngo>>;
    getAllRecords(): Promise<Array<MedicalRecord>>;
    getAllTourismServices(): Promise<Array<TourismService>>;
    getAllVendors(): Promise<Array<Vendor>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getHealthRecord(recordId: string): Promise<HealthRecord>;
    getHealthcareProfessionalById(id: string): Promise<HealthcareProfessional | null>;
    getHealthcareProfessionalsByLocation(city: string): Promise<Array<HealthcareProfessional>>;
    getHealthcareProfessionalsByRole(role: string): Promise<Array<HealthcareProfessional>>;
    getHospitalsByLocation(city: string): Promise<Array<Hospital>>;
    getLuxuryDebtApplications(): Promise<Array<LuxuryDebtService>>;
    getMyRecords(): Promise<Array<MedicalRecord>>;
    getNgosByFocusArea(focusArea: string): Promise<Array<Ngo>>;
    getRecord(recordId: string): Promise<MedicalRecord>;
    getResearchProject(projectId: string): Promise<ResearchProject | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initializeSampleData(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchRecords(filter: RecordFilter): Promise<Array<MedicalRecord>>;
    searchResearchProjects(filter: ResearchFilter): Promise<Array<ResearchProject>>;
    updateHealthcareProfessional(professional: HealthcareProfessional): Promise<void>;
    updateRecord(record: MedicalRecord): Promise<void>;
}
import type { ContactInfo as _ContactInfo, ExternalBlob as _ExternalBlob, HealthRecord as _HealthRecord, HealthcareProfessional as _HealthcareProfessional, Hospital as _Hospital, Location as _Location, MedicalRecord as _MedicalRecord, Ngo as _Ngo, RecordFilter as _RecordFilter, ResearchFilter as _ResearchFilter, ResearchProject as _ResearchProject, TourismService as _TourismService, UserProfile as _UserProfile, UserRole as _UserRole, Vendor as _Vendor, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCorporateHealthcareServices(arg0: string, arg1: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCorporateHealthcareServices(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCorporateHealthcareServices(arg0, arg1);
            return result;
        }
    }
    async addHealthcareProfessional(arg0: HealthcareProfessional): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addHealthcareProfessional(await to_candid_HealthcareProfessional_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addHealthcareProfessional(await to_candid_HealthcareProfessional_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNgo(arg0: Ngo): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNgo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNgo(arg0);
            return result;
        }
    }
    async addTourismService(arg0: TourismService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTourismService(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTourismService(arg0);
            return result;
        }
    }
    async addVendor(arg0: Vendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addVendor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVendor(arg0);
            return result;
        }
    }
    async applyForLuxuryDebt(arg0: LuxuryDebtService): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.applyForLuxuryDebt(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyForLuxuryDebt(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCorporateHealthcare(arg0: Hospital): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createCorporateHealthcare(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCorporateHealthcare(arg0);
            return result;
        }
    }
    async createHealthRecord(arg0: HealthRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createHealthRecord(await to_candid_HealthRecord_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHealthRecord(await to_candid_HealthRecord_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createRecord(arg0: MedicalRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRecord(await to_candid_MedicalRecord_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRecord(await to_candid_MedicalRecord_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createResearchProject(arg0: ResearchProject): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createResearchProject(await to_candid_ResearchProject_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createResearchProject(await to_candid_ResearchProject_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteRecord(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRecord(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRecord(arg0);
            return result;
        }
    }
    async filterDataByLocation(arg0: Location): Promise<{
        professionals: Array<HealthcareProfessional>;
        vendors: Array<Vendor>;
        ngos: Array<Ngo>;
        hospitals: Array<Hospital>;
        services: Array<TourismService>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.filterDataByLocation(arg0);
                return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterDataByLocation(arg0);
            return from_candid_record_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllHospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllHospitals();
            return result;
        }
    }
    async getAllNgos(): Promise<Array<Ngo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNgos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNgos();
            return result;
        }
    }
    async getAllRecords(): Promise<Array<MedicalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecords();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecords();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTourismServices(): Promise<Array<TourismService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTourismServices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTourismServices();
            return result;
        }
    }
    async getAllVendors(): Promise<Array<Vendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllVendors();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllVendors();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthRecord(arg0: string): Promise<HealthRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthRecord(arg0);
                return from_candid_HealthRecord_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthRecord(arg0);
            return from_candid_HealthRecord_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthcareProfessionalById(arg0: string): Promise<HealthcareProfessional | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthcareProfessionalById(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthcareProfessionalById(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthcareProfessionalsByLocation(arg0: string): Promise<Array<HealthcareProfessional>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthcareProfessionalsByLocation(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthcareProfessionalsByLocation(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHealthcareProfessionalsByRole(arg0: string): Promise<Array<HealthcareProfessional>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHealthcareProfessionalsByRole(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHealthcareProfessionalsByRole(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHospitalsByLocation(arg0: string): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospitalsByLocation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospitalsByLocation(arg0);
            return result;
        }
    }
    async getLuxuryDebtApplications(): Promise<Array<LuxuryDebtService>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLuxuryDebtApplications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLuxuryDebtApplications();
            return result;
        }
    }
    async getMyRecords(): Promise<Array<MedicalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecords();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecords();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNgosByFocusArea(arg0: string): Promise<Array<Ngo>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNgosByFocusArea(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNgosByFocusArea(arg0);
            return result;
        }
    }
    async getRecord(arg0: string): Promise<MedicalRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecord(arg0);
                return from_candid_MedicalRecord_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecord(arg0);
            return from_candid_MedicalRecord_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResearchProject(arg0: string): Promise<ResearchProject | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getResearchProject(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResearchProject(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async initializeSampleData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeSampleData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeSampleData();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchRecords(arg0: RecordFilter): Promise<Array<MedicalRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchRecords(to_candid_RecordFilter_n43(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchRecords(to_candid_RecordFilter_n43(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchResearchProjects(arg0: ResearchFilter): Promise<Array<ResearchProject>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchResearchProjects(to_candid_ResearchFilter_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchResearchProjects(to_candid_ResearchFilter_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHealthcareProfessional(arg0: HealthcareProfessional): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHealthcareProfessional(await to_candid_HealthcareProfessional_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHealthcareProfessional(await to_candid_HealthcareProfessional_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateRecord(arg0: MedicalRecord): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRecord(await to_candid_MedicalRecord_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRecord(await to_candid_MedicalRecord_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HealthRecord_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthRecord): Promise<HealthRecord> {
    return await from_candid_record_n37(_uploadFile, _downloadFile, value);
}
async function from_candid_HealthcareProfessional_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HealthcareProfessional): Promise<HealthcareProfessional> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_MedicalRecord_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MedicalRecord): Promise<MedicalRecord> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_ResearchProject_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchProject): Promise<ResearchProject> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n31(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HealthcareProfessional]): Promise<HealthcareProfessional | null> {
    return value.length === 0 ? null : await from_candid_HealthcareProfessional_n23(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResearchProject]): Promise<ResearchProject | null> {
    return value.length === 0 ? null : await from_candid_ResearchProject_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professionals: Array<_HealthcareProfessional>;
    vendors: Array<_Vendor>;
    ngos: Array<_Ngo>;
    hospitals: Array<_Hospital>;
    services: Array<_TourismService>;
}): Promise<{
    professionals: Array<HealthcareProfessional>;
    vendors: Array<Vendor>;
    ngos: Array<Ngo>;
    hospitals: Array<Hospital>;
    services: Array<TourismService>;
}> {
    return {
        professionals: await from_candid_vec_n22(_uploadFile, _downloadFile, value.professionals),
        vendors: value.vendors,
        ngos: value.ngos,
        hospitals: value.hospitals,
        services: value.services
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    verified: boolean;
    contact: _ContactInfo;
    name: string;
    role: string;
    experience: bigint;
    credentials: Array<_ExternalBlob>;
    specialties: Array<string>;
    location: _Location;
}): Promise<{
    id: string;
    verified: boolean;
    contact: ContactInfo;
    name: string;
    role: string;
    experience: bigint;
    credentials: Array<ExternalBlob>;
    specialties: Array<string>;
    location: Location;
}> {
    return {
        id: value.id,
        verified: value.verified,
        contact: value.contact,
        name: value.name,
        role: value.role,
        experience: value.experience,
        credentials: await from_candid_vec_n25(_uploadFile, _downloadFile, value.credentials),
        specialties: value.specialties,
        location: value.location
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: Array<_ExternalBlob>;
    patientId: string;
    treatment: string;
    diagnosis: string;
    patientName: string;
    recordId: string;
}): Promise<{
    documents: Array<ExternalBlob>;
    patientId: string;
    treatment: string;
    diagnosis: string;
    patientName: string;
    recordId: string;
}> {
    return {
        documents: await from_candid_vec_n25(_uploadFile, _downloadFile, value.documents),
        patientId: value.patientId,
        treatment: value.treatment,
        diagnosis: value.diagnosis,
        patientName: value.patientName,
        recordId: value.recordId
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: string;
    professionalProfile: [] | [_HealthcareProfessional];
}): Promise<{
    userType: string;
    professionalProfile?: HealthcareProfessional;
}> {
    return {
        userType: value.userType,
        professionalProfile: record_opt_to_undefined(await from_candid_opt_n33(_uploadFile, _downloadFile, value.professionalProfile))
    };
}
async function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documents: Array<_ExternalBlob>;
    labResults: Array<_MedicalRecord>;
    userId: string;
    imagingStudies: Array<_ExternalBlob>;
    medications: Array<string>;
    medicalHistory: Array<string>;
    personalInfo: {
        dob: string;
        bloodType: string;
        name: string;
        gender: string;
    };
    allergies: Array<string>;
}): Promise<{
    id: string;
    documents: Array<ExternalBlob>;
    labResults: Array<MedicalRecord>;
    userId: string;
    imagingStudies: Array<ExternalBlob>;
    medications: Array<string>;
    medicalHistory: Array<string>;
    personalInfo: {
        dob: string;
        bloodType: string;
        name: string;
        gender: string;
    };
    allergies: Array<string>;
}> {
    return {
        id: value.id,
        documents: await from_candid_vec_n25(_uploadFile, _downloadFile, value.documents),
        labResults: await from_candid_vec_n27(_uploadFile, _downloadFile, value.labResults),
        userId: value.userId,
        imagingStudies: await from_candid_vec_n25(_uploadFile, _downloadFile, value.imagingStudies),
        medications: value.medications,
        medicalHistory: value.medicalHistory,
        personalInfo: value.personalInfo,
        allergies: value.allergies
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    researchers: Array<string>;
    institution: string;
    dataFiles: Array<_ExternalBlob>;
    ethicsApproval: boolean;
    fundingSource: string;
    projectId: string;
    abstract: string;
}): Promise<{
    title: string;
    researchers: Array<string>;
    institution: string;
    dataFiles: Array<ExternalBlob>;
    ethicsApproval: boolean;
    fundingSource: string;
    projectId: string;
    abstract: string;
}> {
    return {
        title: value.title,
        researchers: value.researchers,
        institution: value.institution,
        dataFiles: await from_candid_vec_n25(_uploadFile, _downloadFile, value.dataFiles),
        ethicsApproval: value.ethicsApproval,
        fundingSource: value.fundingSource,
        projectId: value.projectId,
        abstract: value.abstract
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HealthcareProfessional>): Promise<Array<HealthcareProfessional>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HealthcareProfessional_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n26(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MedicalRecord>): Promise<Array<MedicalRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MedicalRecord_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ResearchProject>): Promise<Array<ResearchProject>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ResearchProject_n39(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HealthRecord_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthRecord): Promise<_HealthRecord> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_HealthcareProfessional_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HealthcareProfessional): Promise<_HealthcareProfessional> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function to_candid_MedicalRecord_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MedicalRecord): Promise<_MedicalRecord> {
    return await to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_RecordFilter_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordFilter): _RecordFilter {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_ResearchFilter_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchFilter): _ResearchFilter {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function to_candid_ResearchProject_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ResearchProject): Promise<_ResearchProject> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    documents: Array<ExternalBlob>;
    labResults: Array<MedicalRecord>;
    userId: string;
    imagingStudies: Array<ExternalBlob>;
    medications: Array<string>;
    medicalHistory: Array<string>;
    personalInfo: {
        dob: string;
        bloodType: string;
        name: string;
        gender: string;
    };
    allergies: Array<string>;
}): Promise<{
    id: string;
    documents: Array<_ExternalBlob>;
    labResults: Array<_MedicalRecord>;
    userId: string;
    imagingStudies: Array<_ExternalBlob>;
    medications: Array<string>;
    medicalHistory: Array<string>;
    personalInfo: {
        dob: string;
        bloodType: string;
        name: string;
        gender: string;
    };
    allergies: Array<string>;
}> {
    return {
        id: value.id,
        documents: await to_candid_vec_n10(_uploadFile, _downloadFile, value.documents),
        labResults: await to_candid_vec_n16(_uploadFile, _downloadFile, value.labResults),
        userId: value.userId,
        imagingStudies: await to_candid_vec_n10(_uploadFile, _downloadFile, value.imagingStudies),
        medications: value.medications,
        medicalHistory: value.medicalHistory,
        personalInfo: value.personalInfo,
        allergies: value.allergies
    };
}
async function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    documents: Array<ExternalBlob>;
    patientId: string;
    treatment: string;
    diagnosis: string;
    patientName: string;
    recordId: string;
}): Promise<{
    documents: Array<_ExternalBlob>;
    patientId: string;
    treatment: string;
    diagnosis: string;
    patientName: string;
    recordId: string;
}> {
    return {
        documents: await to_candid_vec_n10(_uploadFile, _downloadFile, value.documents),
        patientId: value.patientId,
        treatment: value.treatment,
        diagnosis: value.diagnosis,
        patientName: value.patientName,
        recordId: value.recordId
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    researchers: Array<string>;
    institution: string;
    dataFiles: Array<ExternalBlob>;
    ethicsApproval: boolean;
    fundingSource: string;
    projectId: string;
    abstract: string;
}): Promise<{
    title: string;
    researchers: Array<string>;
    institution: string;
    dataFiles: Array<_ExternalBlob>;
    ethicsApproval: boolean;
    fundingSource: string;
    projectId: string;
    abstract: string;
}> {
    return {
        title: value.title,
        researchers: value.researchers,
        institution: value.institution,
        dataFiles: await to_candid_vec_n10(_uploadFile, _downloadFile, value.dataFiles),
        ethicsApproval: value.ethicsApproval,
        fundingSource: value.fundingSource,
        projectId: value.projectId,
        abstract: value.abstract
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userType: string;
    professionalProfile?: HealthcareProfessional;
}): Promise<{
    userType: string;
    professionalProfile: [] | [_HealthcareProfessional];
}> {
    return {
        userType: value.userType,
        professionalProfile: value.professionalProfile ? candid_some(await to_candid_HealthcareProfessional_n8(_uploadFile, _downloadFile, value.professionalProfile)) : candid_none()
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patientId?: string;
    diagnosis?: string;
    dateRange?: {
        endDate: string;
        startDate: string;
    };
}): {
    patientId: [] | [string];
    diagnosis: [] | [string];
    dateRange: [] | [{
            endDate: string;
            startDate: string;
        }];
} {
    return {
        patientId: value.patientId ? candid_some(value.patientId) : candid_none(),
        diagnosis: value.diagnosis ? candid_some(value.diagnosis) : candid_none(),
        dateRange: value.dateRange ? candid_some(value.dateRange) : candid_none()
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    institution?: string;
    ethicsApproval?: boolean;
    keyword?: string;
}): {
    institution: [] | [string];
    ethicsApproval: [] | [boolean];
    keyword: [] | [string];
} {
    return {
        institution: value.institution ? candid_some(value.institution) : candid_none(),
        ethicsApproval: value.ethicsApproval ? candid_some(value.ethicsApproval) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    verified: boolean;
    contact: ContactInfo;
    name: string;
    role: string;
    experience: bigint;
    credentials: Array<ExternalBlob>;
    specialties: Array<string>;
    location: Location;
}): Promise<{
    id: string;
    verified: boolean;
    contact: _ContactInfo;
    name: string;
    role: string;
    experience: bigint;
    credentials: Array<_ExternalBlob>;
    specialties: Array<string>;
    location: _Location;
}> {
    return {
        id: value.id,
        verified: value.verified,
        contact: value.contact,
        name: value.name,
        role: value.role,
        experience: value.experience,
        credentials: await to_candid_vec_n10(_uploadFile, _downloadFile, value.credentials),
        specialties: value.specialties,
        location: value.location
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MedicalRecord>): Promise<Array<_MedicalRecord>> {
    return await Promise.all(value.map(async (x)=>await to_candid_MedicalRecord_n17(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
